<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulaires</title>
</head>
<body>
    <header>
        <h1>Les formulaires et PHP</h1>
    </header>
    <main>
        <form action="hello.php" method="POST">
            <fieldset>
                <legend>A qui voulez-vous dire bonjour ?</legend>
                <div>
                    <label for="firstname">Prénom</label>
                    <input type="text" id="firstname" name="firstname">
                </div>
                <input type="submit" value="Valider">
            </fieldset>
        </form>

        <?php if (isset($message)) { ?>
            <p><?=$message;?></p>
        <?php } ?>
    </main>
</body>
</html>